name: "Parse CHANGELOG and extract bump version"
description: "Parses the CHANGELOG to new version and returns the version."
author: "Jernej Frank"

inputs:
  changelog_template_url:
    description: "URL to the CHANGELOG_TEMPLATE.md in the action's repository"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Action Repository (to access bump_version.sh and CHANGELOG_TEMPLATE.md)
      uses: actions/checkout@v4
      with:
        repository: jernejfrank/update_changelog_get_semver
        ref: main
        path: action_repo  # This places the action in a subdirectory

    - name: Copy CHANGELOG to action repo
      run: |
        cp CHANGELOG.md ./action_repo/CHANGELOG.md
      shell: bash

    - name: Make version script executable
      run: chmod +x ./action_repo/parse_changelog.sh
      shell: bash

    - name: Run version bump script (updates changelog)
      id: bump_version
      run: |
        cd ./action_repo
        ./parse_changelog.sh
        cd ../
      shell: bash

    - name: Copy CHANGELOG back to main repo
      run: |
        cp ./action_repo/CHANGELOG.md ./CHANGELOG.md 
      shell: bash
    
    - name: Cleanup temp files
      run: |
        rm -rf action_repo  # This will delete the 'action_repo' folder
      continue-on-error: true
      shell: bash
